
language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
os:
  - linux

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then echo "dependencies"; fi
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then echo "build"; fi
after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then echo "after success"; fi
