
name: smithproxy
version: '0.9.2'
summary: Fast and featured transparent TCP/UDP/TLS proxy
description: |
 Smithproxy is fast transparent TCP/UDP/TLS (SSL) proxy. It's highly configurable
 and featured.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

base: core18

layout:
  /etc:
    bind: $SNAP_DATA/etc

  /usr/share/smithproxy:
    bind: $SNAP_DATA/usr/share/smithproxy

  /var/local/smithproxy:
    type: tmpfs

parts:
  smithproxy-core:
    plugin: cmake
    source-type: git
    source: https://github.com/astibal/smithproxy
    source-branch: master
    build-packages:
      - g++-8
      - make
      - cmake
      - libcli-dev
      - libconfig++-dev
      - libunwind-dev
      - python3-dev
      - libssl-dev

    stage-packages:
      - libcli1.9
      - libconfig++9v5
      - libunwind8
      - inetutils-telnet


apps:
  smithproxy:
    daemon: simple
    command: bin/smithproxy
    plugs:
      - network
      - network-bind
      - network-control

  smithd:
    daemon: simple
    command: bin/smithd
    plugs:
      - network
      - network-bind

  cli:
    command: bin/sx_cli

  regencert:
    command: bin/sx_regencerts

  passwd:
    command: bin/sx_passwd

  autoportalcert:
    command: bin/sx_autoportalcert

  certinfo-ca:
    command: bin/sx_certinfo_ca

  sx-ctl:
    command: bin/sx_ctl
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control


  sx-network:
    command: bin/sx_network
    plugs:
      - network
      - network-bind
      - network-control
